INSERT INTO CATALOG(PRODUCT_ID,PRODUCT_NAME,STOCK,UNIT_PRICE) VALUES ('CATALOG-001','BERLIN',100,1500);
INSERT INTO CATALOG(PRODUCT_ID,PRODUCT_NAME,STOCK,UNIT_PRICE) VALUES ('CATALOG-002','TOKYO',190,2500);
INSERT INTO CATALOG(PRODUCT_ID,PRODUCT_NAME,STOCK,UNIT_PRICE) VALUES ('CATALOG-003','SEOUL',300,4200);