token: 
    expiration_time: 86422222
    secret: config_user_token_change_dev

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        dirver-class-name: org.h2.Driver
        username: sa
        password: '{cipher}2106b4144de968165b2f30b1172c9ba728570d0d9d99ad4fef771b6543fd219b'

gateway: 
    ip: 192.168.0.8