server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://D:\study\spring-cloud\
          uri: https://github.com/sos9210/spring-cloud.git
